Rewrited auth scripts
CESNET/proxyidp-nagios-scripts pull request #8
Opened 2020-02-16 18:05 UTC by pajavyskocil

* All script now timeouts if the script runs too long
* Login functions is now moved to separate helper scripts

2020-02-17 12:20 UTC, dBucik requested changes

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_script/saml_auth_test_muni_active.sh
> +fi
Add a newline please

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_active_saml.sh
> +exit ${STATUS}
Missing newline at the end of the file

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_config.sh
> +TIMEOUT_TIME=40
Missing newline

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_oidc.sh
> +exit 0
missing newline

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_oidc.sh
> +if [ ${CESNET_RC} -gt 2 ]; then
There is a lot of code that is common in different files. Perhaps you could create a separated file with functions to handle the result and just pass it different messages (if they differ of course)?

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_saml.sh
> +exit 0
missing newline

2020-02-17 12:20 UTC, dBucik commented on proxy_idp_auth_test_script/saml_auth_test_muni.sh
> +fi
missing newline

2020-02-17 18:31 UTC, pajavyskocil commented
Added missing newlines

2020-02-19 12:17 UTC, pajavyskocil commented
Merging after discussion with Dominik Bučík

2020-02-19 12:17 UTC, merged